[package]
name = "dap-types"
version = "0.0.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
serde = "1.0.193"
serde_json = "1.0.108"
serde_derive = "1.0.193"
ahash = "0.8.6"
