[package]
name = "dap-types"
version = "0.0.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
serde = "1.0.194"
serde_json = "1.0.110"
serde_derive = "1.0.194"
ahash = "0.8.7"
