[package]
name = "dap-types"
version = "0.0.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.141"
serde_derive = "1.0.219"
ahash = "0.8.12"
