[package]
name = "dap-types"
version = "0.0.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
serde = "1.0.195"
serde_json = "1.0.111"
serde_derive = "1.0.195"
ahash = "0.8.7"
