[package]
name = "dm-langserver"
version = "1.7.3"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
url = "2.4.1"
serde = "1.0.188"
serde_json = "1.0.107"
serde_derive = "1.0.188"
bincode = "1.3.3"
jsonrpc-core = "18.0.0"
lsp-types = "0.94.1"
dap-types = { path = "../dap-types" }
dreammaker = { path = "../dreammaker" }
dreamchecker = { path = "../dreamchecker" }
interval-tree = { path = "../interval-tree" }
libc = "0.2.148"
regex = "1.9.5"
lazy_static = "1.4"
ahash = "0.8.3"

[build-dependencies]
chrono = "0.4.30"
git2 = { version = "0.18.0", default-features = false }
