[package]
name = "dm-langserver"
version = "1.7.3"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2018"

[dependencies]
url = "2.3.1"
serde = "1.0.163"
serde_json = "1.0.96"
serde_derive = "1.0.163"
bincode = "1.3.3"
jsonrpc-core = "18.0.0"
lsp-types = "0.94.0"
dap-types = { path = "../dap-types" }
dreammaker = { path = "../dreammaker" }
dreamchecker = { path = "../dreamchecker" }
interval-tree = { path = "../interval-tree" }
libc = "0.2.144"
regex = "1.8.3"
lazy_static = "1.4"
ahash = "0.8.3"

[build-dependencies]
chrono = "0.4.26"
git2 = { version = "0.17.2", default-features = false }
