[package]
name = "dm-langserver"
version = "1.8.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
url = "2.5.0"
serde = "1.0.197"
serde_json = "1.0.114"
serde_derive = "1.0.197"
bincode = "1.3.3"
jsonrpc-core = "18.0.0"
lsp-types = "0.95.0"
dap-types = { path = "../dap-types" }
dreammaker = { path = "../dreammaker" }
dreamchecker = { path = "../dreamchecker" }
interval-tree = { path = "../interval-tree" }
libc = "0.2.153"
regex = "1.10.3"
lazy_static = "1.4"
ahash = "0.8.11"

[build-dependencies]
chrono = "0.4.35"
git2 = { version = "0.18.2", default-features = false }
