[package]
name = "dmm-tools-cli"
version = "1.8.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
description = "BYOND map rendering and analysis tools powered by SpacemanDMM"
edition = "2021"

[[bin]]
name = "dmm-tools"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
serde = "1.0.194"
serde_derive = "1.0.194"
serde_json = "1.0.110"
rayon = "1.8.0"
dreammaker = { path = "../dreammaker" }
dmm-tools = { path = "../dmm-tools" }
ahash = "0.8.7"

[build-dependencies]
chrono = "0.4.31"
git2 = { version = "0.18.1", default-features = false }
