[package]
name = "dmm-tools-cli"
version = "1.7.3"
authors = ["Tad Hardesty <tad@platymuus.com>"]
description = "BYOND map rendering and analysis tools powered by SpacemanDMM"
edition = "2018"

[[bin]]
name = "dmm-tools"
path = "src/main.rs"

[dependencies]
structopt = "0.3.26"
structopt-derive = "0.4.18"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
rayon = "1.7.0"
dreammaker = { path = "../dreammaker" }
dmm-tools = { path = "../dmm-tools", features = ["png"] }
ahash = "0.8.3"

[build-dependencies]
chrono = "0.4.26"
git2 = { version = "0.17.2", default-features = false }
