[package]
name = "dmdoc"
version = "1.7.3"
authors = ["Tad Hardesty <tad@platymuus.com>"]
homepage = "https://github.com/SpaceManiac/SpacemanDMM/blob/master/crates/dmdoc/README.md"
edition = "2018"

[dependencies]
dreammaker = { path = "../dreammaker" }
pulldown-cmark = "0.9.3"
tera = "1.18.1"
serde = "1.0.163"
serde_derive = "1.0.163"
walkdir = "2.3.3"
git2 = { version = "0.17.1", default-features = false }

[dev-dependencies]
walkdir = "2.3.3"

[build-dependencies]
chrono = "0.4.24"
git2 = { version = "0.17.1", default-features = false }
