[package]
name = "tinydmi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
eyre = "0.6.11"
ahash = "0.8.6"
indexmap = "2.1.0"
