[package]
name = "dreammaker"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
interval-tree = { path = "../interval-tree" }
builtins-proc-macro = { path = "../builtins-proc-macro" }
bitflags = "2.4.0"
termcolor = "1.3.0"
ordered-float = "3.9.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_derive = "1.0.188"
toml = "0.8.0"
phf = { version = "0.11.2", features = ["macros"] }
color_space = "0.5.3"
ahash = "0.8.3"
indexmap = "2.0.0"

[dev-dependencies]
walkdir = "2.4.0"
