[package]
name = "dreammaker"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2021"

[dependencies]
interval-tree = { path = "../interval-tree" }
builtins-proc-macro = { path = "../builtins-proc-macro" }
bitflags = "2.4.1"
termcolor = "1.3.0"
ordered-float = "4.1.1"
serde = { version = "1.0.190", features = ["derive"] }
serde_derive = "1.0.190"
toml = "0.8.6"
phf = { version = "0.11.2", features = ["macros"] }
color_space = "0.5.3"
ahash = "0.8.6"
indexmap = "2.0.2"
derivative = "2.2.0"
get-size = { version = "0.1.4", features = ["derive"] }

[dev-dependencies]
walkdir = "2.4.0"
