[package]
name = "dreammaker"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2018"

[dependencies]
interval-tree = { path = "../interval-tree" }
builtins-proc-macro = { path = "../builtins-proc-macro" }
lodepng = "3.7.2"
bitflags = "2.3.1"
termcolor = "1.1.3"
ordered-float = "3.7.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_derive = "1.0.163"
toml = "0.7.4"
phf = { version = "0.11.1", features = ["macros"] }
color_space = "0.5.3"
ahash = "0.8.3"
indexmap = "1.9.3"
derivative = "2.2.0"

[dev-dependencies]
walkdir = "2.3.3"
