[package]
name = "dmm-tools"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2018"

[dependencies]
ndarray = "0.15.6"
rand = "0.8.5"
dreammaker = { path = "../dreammaker" }
tinydmi = { path = "../tinydmi"}
indexmap = "2.0.0"
ahash = "0.8.3"
either = "1.8.1"
typed-arena = "2.0.2"
image = "0.24.6"
png = "0.17.9"
eyre = "0.6.8"

[dependencies.bytemuck]
version = "1.13.1"
features = ["derive"]

[dependencies.gfx_core]
version = "0.9.2"
optional = true

[dev-dependencies]
walkdir = "2.3.3"
