[package]
name = "dmm-tools"
version = "0.1.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]
edition = "2018"

[dependencies]
inflate = "0.4.5"
ndarray = "0.15.6"
rand = "0.8.5"
dreammaker = { path = "../dreammaker" }
lodepng = "3.7.2"
indexmap = "2.0.0"
ahash = "0.8.3"
either = "1.8.1"

[dependencies.bytemuck]
version = "1.13.1"
features = ["derive"]

[dependencies.bumpalo]
version = "3.13.0"
features = ["collections"]

[dependencies.png]
version = "0.17.9"
optional = true

[dependencies.gfx_core]
version = "0.9.2"
optional = true

[dependencies.gif]
version = "0.12.0"
optional = true

[dev-dependencies]
walkdir = "2.3.3"
